"""mode aware tracking

Revision ID: 4252c27a3224
Revises: 5496843aadd5
Create Date: 2026-04-07 15:45:23.382272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4252c27a3224'
down_revision: Union[str, Sequence[str], None] = '5496843aadd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_evaluations', sa.Column('score_min_applied', sa.Float(), nullable=True))
    op.add_column('signal_evaluations', sa.Column('config_version', sa.String(length=100), nullable=True))
    op.add_column('trade_outcomes', sa.Column('momentum_score', sa.Float(), nullable=True))
    op.add_column('trade_outcomes', sa.Column('score_min_applied', sa.Float(), nullable=True))
    op.add_column('trade_outcomes', sa.Column('config_version', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_outcomes', 'config_version')
    op.drop_column('trade_outcomes', 'score_min_applied')
    op.drop_column('trade_outcomes', 'momentum_score')
    op.drop_column('signal_evaluations', 'config_version')
    op.drop_column('signal_evaluations', 'score_min_applied')
    # ### end Alembic commands ###
