"""audit tables

Revision ID: 5496843aadd5
Revises: 91f1d5074475
Create Date: 2026-04-06 11:40:50.225536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5496843aadd5'
down_revision: Union[str, Sequence[str], None] = '91f1d5074475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_findings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('audit_run_id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_audit_run_id'), 'audit_findings', ['audit_run_id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('audit_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_type_time', 'audit_runs', ['audit_type', 'started_at'], unique=False)
    op.create_index(op.f('ix_audit_runs_audit_type'), 'audit_runs', ['audit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_runs_audit_type'), table_name='audit_runs')
    op.drop_index('idx_audit_type_time', table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_audit_findings_audit_run_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    # ### end Alembic commands ###
