"""entry quality diagnostics

Revision ID: 5fd4bf08acfe
Revises: a90c97d693c0
Create Date: 2026-04-07 23:55:20.704133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd4bf08acfe'
down_revision: Union[str, Sequence[str], None] = 'a90c97d693c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_evaluations', sa.Column('entry_diagnostics', sa.JSON(), nullable=True))
    op.add_column('signal_evaluations', sa.Column('entry_quality_label', sa.String(length=20), nullable=True))
    op.add_column('signal_evaluations', sa.Column('late_entry_risk', sa.String(length=20), nullable=True))
    op.add_column('trade_outcomes', sa.Column('entry_quality_label', sa.String(length=20), nullable=True))
    op.add_column('trade_outcomes', sa.Column('late_entry_risk', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_outcomes', 'late_entry_risk')
    op.drop_column('trade_outcomes', 'entry_quality_label')
    op.drop_column('signal_evaluations', 'late_entry_risk')
    op.drop_column('signal_evaluations', 'entry_quality_label')
    op.drop_column('signal_evaluations', 'entry_diagnostics')
    # ### end Alembic commands ###
