"""config snapshot

Revision ID: 8245ff6c4af2
Revises: 4252c27a3224
Create Date: 2026-04-07 15:59:43.349510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8245ff6c4af2'
down_revision: Union[str, Sequence[str], None] = '4252c27a3224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_evaluations', sa.Column('config_snapshot', sa.JSON(), nullable=True))
    op.add_column('trade_outcomes', sa.Column('config_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_outcomes', 'config_snapshot')
    op.drop_column('signal_evaluations', 'config_snapshot')
    # ### end Alembic commands ###
