"""initial schema

Revision ID: 91f1d5074475
Revises: 
Create Date: 2026-04-05 23:21:57.167856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f1d5074475'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('avg_pnl', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_hold_sec', sa.Integer(), nullable=True),
    sa.Column('best_regime', sa.String(length=30), nullable=True),
    sa.Column('worst_regime', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_profiles_coin'), 'coin_profiles', ['coin'], unique=False)
    op.create_table('dataset_registry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('feature_version', sa.String(length=100), nullable=True),
    sa.Column('label_type', sa.String(length=50), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coins', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiment_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('baseline_params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('baseline_results', sa.JSON(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feat_coin_time', 'feature_snapshots', ['coin', 'timestamp'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('feature_version', sa.String(length=100), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_name_version', 'model_registry', ['name', 'version'], unique=False)
    op.create_table('regime_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('volatility_level', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regime_coin_time', 'regime_labels', ['coin', 'timestamp'], unique=False)
    op.create_table('replay_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('run_type', sa.String(length=30), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coins', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('events_processed', sa.Integer(), nullable=True),
    sa.Column('elapsed_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('micro_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=30), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('trade_outcome_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_action', 'signal_evaluations', ['action'], unique=False)
    op.create_index('idx_signal_coin_time', 'signal_evaluations', ['coin', 'timestamp'], unique=False)
    op.create_index(op.f('ix_signal_evaluations_coin'), 'signal_evaluations', ['coin'], unique=False)
    op.create_index(op.f('ix_signal_evaluations_timestamp'), 'signal_evaluations', ['timestamp'], unique=False)
    op.create_table('trade_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('entry_tag', sa.String(length=50), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('hold_seconds', sa.Integer(), nullable=True),
    sa.Column('regime', sa.String(length=30), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('micro_score', sa.Float(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('high_water_mark', sa.Float(), nullable=True),
    sa.Column('entry_features', sa.JSON(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_coin_entry', 'trade_outcomes', ['coin', 'entry_time'], unique=False)
    op.create_index('idx_trade_mode', 'trade_outcomes', ['mode'], unique=False)
    op.create_index('idx_trade_regime', 'trade_outcomes', ['regime'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_coin'), 'trade_outcomes', ['coin'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_entry_time'), 'trade_outcomes', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trade_outcomes_exit_time'), 'trade_outcomes', ['exit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_outcomes_exit_time'), table_name='trade_outcomes')
    op.drop_index(op.f('ix_trade_outcomes_entry_time'), table_name='trade_outcomes')
    op.drop_index(op.f('ix_trade_outcomes_coin'), table_name='trade_outcomes')
    op.drop_index('idx_trade_regime', table_name='trade_outcomes')
    op.drop_index('idx_trade_mode', table_name='trade_outcomes')
    op.drop_index('idx_trade_coin_entry', table_name='trade_outcomes')
    op.drop_table('trade_outcomes')
    op.drop_index(op.f('ix_signal_evaluations_timestamp'), table_name='signal_evaluations')
    op.drop_index(op.f('ix_signal_evaluations_coin'), table_name='signal_evaluations')
    op.drop_index('idx_signal_coin_time', table_name='signal_evaluations')
    op.drop_index('idx_signal_action', table_name='signal_evaluations')
    op.drop_table('signal_evaluations')
    op.drop_table('replay_runs')
    op.drop_index('idx_regime_coin_time', table_name='regime_labels')
    op.drop_table('regime_labels')
    op.drop_index('idx_model_name_version', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index('idx_feat_coin_time', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_table('experiment_runs')
    op.drop_table('dataset_registry')
    op.drop_index(op.f('ix_coin_profiles_coin'), table_name='coin_profiles')
    op.drop_table('coin_profiles')
    # ### end Alembic commands ###
