"""add diagnostic_trace to signal_evaluations

Revision ID: a90c97d693c0
Revises: fae64499ead3
Create Date: 2026-04-07 19:43:32.188356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90c97d693c0'
down_revision: Union[str, Sequence[str], None] = 'fae64499ead3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_evaluations', sa.Column('diagnostic_trace', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_evaluations', 'diagnostic_trace')
    # ### end Alembic commands ###
