"""decision stages

Revision ID: fae64499ead3
Revises: 8245ff6c4af2
Create Date: 2026-04-07 17:14:34.227853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae64499ead3'
down_revision: Union[str, Sequence[str], None] = '8245ff6c4af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_evaluations', sa.Column('decision_stage', sa.String(length=30), nullable=True))
    op.add_column('signal_evaluations', sa.Column('decision_trace', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_evaluations', 'decision_trace')
    op.drop_column('signal_evaluations', 'decision_stage')
    # ### end Alembic commands ###
